CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL IDENTITY (1,1),
	[Email] NVARCHAR(50) NOT NULL,
	[Pseudo] NVARCHAR(50) NOT NULL,
	[Password] NVARCHAR(50) NOT NULL,
	[Salt] NVARCHAR(200) NOT NULL,
	[BirthDate] DATE NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT 1,
	[IsAdmin] BIT NOT NULL DEFAULT 0,
	CONSTRAINT PK_Users PRIMARY KEY (Id)
)
